#! /usr/bin/env python3

"""
Unittest implementation to convert a service request for operator/plan
"""

# Unittest context !
import sys
import os
from pathlib import Path
sys.path.append(os.fspath(Path().resolve()))
# end of unittest context

from noops.external.processing import Processing # pylint: disable=import-error,wrong-import-position

class ProcessingUnittest(Processing):
    """Unittest processing"""
    def convert(self, service_request, name): # pylint: disable=unused-argument
        """implement abstract method Processing.convert"""
        return [
            {
                "apiVersion": "unittest.local/v1",
                "kind": "Test",
                "spec": {
                    "key": service_request.get("key")
                }
            }
        ]

ProcessingUnittest().run()
